// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"chandao-mini/backend/core/initialization"
	"chandao-mini/backend/core/zentao"
	"os"
)

// Injectors from wire.go:

// InitializeHTTPApp 初始化HTTP应用
// 使用wire自动生成依赖注入代码
func InitializeHTTPApp(config *AppConfig) (Application, error) {
	initService := provideInitService(config)
	client := provideZentaoClient(config, initService)
	dependencies := NewDependencies(initService, client)
	application := provideHTTPApp(config, dependencies)
	return application, nil
}

// InitializeWailsApp 初始化Wails应用
// 使用wire自动生成依赖注入代码
func InitializeWailsApp(config *AppConfig) (Application, error) {
	initService := provideInitService(config)
	client := provideZentaoClient(config, initService)
	dependencies := NewDependencies(initService, client)
	application := provideWailsApp(config, dependencies)
	return application, nil
}

// wire.go:

// provideInitService 提供InitService实例
func provideInitService(config *AppConfig) *initialization.InitService {
	return initialization.NewInitService(
		config.AuthConfigPath,
		config.AuthDBPath,
		config.EncryptionKey,
	)
}

// provideZentaoClient 提供ZentaoClient实例
func provideZentaoClient(config *AppConfig, initService *initialization.InitService) *zentao.Client {

	zentaoServer, zentaoAccount, zentaoPassword := initialization.LoadZentaoConfig(initService)

	if config.ZentaoServer != "" {
		zentaoServer = config.ZentaoServer
	}
	if config.ZentaoAccount != "" {
		zentaoAccount = config.ZentaoAccount
	}
	if config.ZentaoPassword != "" {
		zentaoPassword = config.ZentaoPassword
	}

	if zentaoServer == "" {
		zentaoServer = os.Getenv("ZENTAO_SERVER")
	}
	if zentaoAccount == "" {
		zentaoAccount = os.Getenv("ZENTAO_ACCOUNT")
	}
	if zentaoPassword == "" {
		zentaoPassword = os.Getenv("ZENTAO_PASSWORD")
	}

	return zentao.NewClient(zentaoServer, zentaoAccount, zentaoPassword)
}

// provideHTTPApp 提供HTTPApp并绑定到Application接口
func provideHTTPApp(config *AppConfig, deps *Dependencies) Application {
	return NewHTTPApp(config, deps)
}

// provideWailsApp 提供WailsApp并绑定到Application接口
func provideWailsApp(config *AppConfig, deps *Dependencies) Application {
	return NewWailsApp(config, deps)
}
