// Code generated by hertz generator.

package zentao

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcphandleactiongetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetbugsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetexecutionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcppingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetprojectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetstoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgettasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgettimelogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcphandlelisttoolsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcphandlegettoolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcpgetusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mcphandleactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbugsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexecutionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusersallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcurrentuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccountinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinitstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpersonaltimelogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectoverviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _schedulerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscheduleralllogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _previewschedulerreportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listschedulertasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteschedulertaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getschedulertasklogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runschedulertasknowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toggleschedulertaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateschedulertaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createschedulertaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testschedulerwebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _timelogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettimeloganalysisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettimelogdashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettimelogeffortsMw() []app.HandlerFunc {
	// your code...
	return nil
}
