// Code generated by hertz generator. DO NOT EDIT.

package zentao

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	zentao "github.com/yi-nology/zentao-mini/backend/biz/handler/zentao"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	root.GET("/mcp", append(_mcphandleactiongetMw(), zentao.MCPHandleActionGet)...)
	_mcp := root.Group("/mcp", _mcpMw()...)
	_mcp.GET("/bugs", append(_mcpgetbugsMw(), zentao.MCPGetBugs)...)
	_mcp.GET("/executions", append(_mcpgetexecutionsMw(), zentao.MCPGetExecutions)...)
	_mcp.GET("/ping", append(_mcppingMw(), zentao.MCPPing)...)
	_mcp.GET("/products", append(_mcpgetproductsMw(), zentao.MCPGetProducts)...)
	_mcp.GET("/projects", append(_mcpgetprojectsMw(), zentao.MCPGetProjects)...)
	_mcp.GET("/stories", append(_mcpgetstoriesMw(), zentao.MCPGetStories)...)
	_mcp.GET("/tasks", append(_mcpgettasksMw(), zentao.MCPGetTasks)...)
	_mcp.GET("/timelog", append(_mcpgettimelogMw(), zentao.MCPGetTimelog)...)
	_mcp.GET("/tools", append(_mcphandlelisttoolsMw(), zentao.MCPHandleListTools)...)
	_tools := _mcp.Group("/tools", _toolsMw()...)
	_tools.GET("/:name", append(_mcphandlegettoolMw(), zentao.MCPHandleGetTool)...)
	_mcp.GET("/users", append(_mcpgetusersMw(), zentao.MCPGetUsers)...)
	root.POST("/mcp", append(_mcphandleactionMw(), zentao.MCPHandleAction)...)
	{
		_api := root.Group("/api", _apiMw()...)
		_api.GET("/healthz", append(_healthcheckMw(), zentao.HealthCheck)...)
		_api.GET("/version", append(_getversionMw(), zentao.GetVersion)...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.GET("/bugs", append(_getbugsMw(), zentao.GetBugs)...)
			{
				_builds := _v1.Group("/builds", _buildsMw()...)
				_builds.GET("/execution", append(_getbuildsbyexecutionMw(), zentao.GetBuildsByExecution)...)
				_builds.GET("/project", append(_getbuildsbyprojectMw(), zentao.GetBuildsByProject)...)
			}
			_v1.GET("/dashboard", append(_getdashboardMw(), zentao.GetDashboard)...)
			_v1.GET("/executions", append(_getexecutionsMw(), zentao.GetExecutions)...)
			_v1.GET("/products", append(_getproductsMw(), zentao.GetProducts)...)
			_v1.GET("/projects", append(_getprojectsMw(), zentao.GetProjects)...)
			_v1.GET("/search", append(_searchMw(), zentao.Search)...)
			_v1.GET("/stories", append(_getstoriesMw(), zentao.GetStories)...)
			_v1.GET("/tasks", append(_gettasksMw(), zentao.GetTasks)...)
			_v1.GET("/users", append(_getusersMw(), zentao.GetUsers)...)
			_users := _v1.Group("/users", _usersMw()...)
			_users.GET("/all", append(_getusersallMw(), zentao.GetUsersAll)...)
			_users.GET("/current", append(_getcurrentuserMw(), zentao.GetCurrentUser)...)
			{
				_init := _v1.Group("/init", _initMw()...)
				_init.GET("/account", append(_getaccountinfoMw(), zentao.GetAccountInfo)...)
				_init.GET("/status", append(_getinitstatusMw(), zentao.GetInitStatus)...)
			}
			{
				_personal := _v1.Group("/personal", _personalMw()...)
				_personal.GET("/timelog", append(_getpersonaltimelogMw(), zentao.GetPersonalTimelog)...)
			}
			{
				_project := _v1.Group("/project", _projectMw()...)
				_project.GET("/overview", append(_getprojectoverviewMw(), zentao.GetProjectOverview)...)
			}
			{
				_scheduler := _v1.Group("/scheduler", _schedulerMw()...)
				_scheduler.GET("/logs", append(_getscheduleralllogsMw(), zentao.GetSchedulerAllLogs)...)
				_scheduler.POST("/preview", append(_previewschedulerreportMw(), zentao.PreviewSchedulerReport)...)
				_scheduler.GET("/tasks", append(_listschedulertasksMw(), zentao.ListSchedulerTasks)...)
				_tasks := _scheduler.Group("/tasks", _tasksMw()...)
				_tasks.DELETE("/:id", append(_deleteschedulertaskMw(), zentao.DeleteSchedulerTask)...)
				_id := _tasks.Group("/:id", _idMw()...)
				_id.GET("/logs", append(_getschedulertasklogsMw(), zentao.GetSchedulerTaskLogs)...)
				_id.POST("/run", append(_runschedulertasknowMw(), zentao.RunSchedulerTaskNow)...)
				_id.PATCH("/toggle", append(_toggleschedulertaskMw(), zentao.ToggleSchedulerTask)...)
				_tasks.PUT("/:id", append(_updateschedulertaskMw(), zentao.UpdateSchedulerTask)...)
				_scheduler.POST("/tasks", append(_createschedulertaskMw(), zentao.CreateSchedulerTask)...)
				_scheduler.POST("/test-webhook", append(_testschedulerwebhookMw(), zentao.TestSchedulerWebhook)...)
			}
			{
				_timelog := _v1.Group("/timelog", _timelogMw()...)
				_timelog.GET("/analysis", append(_gettimeloganalysisMw(), zentao.GetTimelogAnalysis)...)
				_timelog.GET("/dashboard", append(_gettimelogdashboardMw(), zentao.GetTimelogDashboard)...)
				_timelog.GET("/efforts", append(_gettimelogeffortsMw(), zentao.GetTimelogEfforts)...)
			}
		}
	}
}
