// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: zentao.proto

package zentao

import (
	_ "github.com/yi-nology/zentao-mini/backend/biz/model/api"
	common "github.com/yi-nology/zentao-mini/backend/biz/model/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionReq) Reset() {
	*x = GetVersionReq{}
	mi := &file_zentao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionReq) ProtoMessage() {}

func (x *GetVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionReq.ProtoReflect.Descriptor instead.
func (*GetVersionReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{0}
}

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_zentao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{1}
}

type GetProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReq) Reset() {
	*x = GetProductsReq{}
	mi := &file_zentao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReq) ProtoMessage() {}

func (x *GetProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReq.ProtoReflect.Descriptor instead.
func (*GetProductsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{2}
}

type GetProjectsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsReq) Reset() {
	*x = GetProjectsReq{}
	mi := &file_zentao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsReq) ProtoMessage() {}

func (x *GetProjectsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsReq.ProtoReflect.Descriptor instead.
func (*GetProjectsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectsReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetExecutionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionsReq) Reset() {
	*x = GetExecutionsReq{}
	mi := &file_zentao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionsReq) ProtoMessage() {}

func (x *GetExecutionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionsReq.ProtoReflect.Descriptor instead.
func (*GetExecutionsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{4}
}

func (x *GetExecutionsReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetExecutionsReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetBugsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProjectId     int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	SpecificDate  string                 `protobuf:"bytes,7,opt,name=specific_date,json=specificDate,proto3" json:"specific_date,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBugsReq) Reset() {
	*x = GetBugsReq{}
	mi := &file_zentao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBugsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBugsReq) ProtoMessage() {}

func (x *GetBugsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBugsReq.ProtoReflect.Descriptor instead.
func (*GetBugsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{5}
}

func (x *GetBugsReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetBugsReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetBugsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBugsReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetBugsReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetBugsReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetBugsReq) GetSpecificDate() string {
	if x != nil {
		return x.SpecificDate
	}
	return ""
}

func (x *GetBugsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBugsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetStoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProjectId     int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   int32                  `protobuf:"varint,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	SpecificDate  string                 `protobuf:"bytes,7,opt,name=specific_date,json=specificDate,proto3" json:"specific_date,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoriesReq) Reset() {
	*x = GetStoriesReq{}
	mi := &file_zentao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoriesReq) ProtoMessage() {}

func (x *GetStoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoriesReq.ProtoReflect.Descriptor instead.
func (*GetStoriesReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoriesReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetStoriesReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *GetStoriesReq) GetExecutionId() int32 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *GetStoriesReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetStoriesReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetStoriesReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetStoriesReq) GetSpecificDate() string {
	if x != nil {
		return x.SpecificDate
	}
	return ""
}

func (x *GetStoriesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStoriesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ExecutionId   int32                  `protobuf:"varint,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,3,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksReq) Reset() {
	*x = GetTasksReq{}
	mi := &file_zentao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksReq) ProtoMessage() {}

func (x *GetTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksReq.ProtoReflect.Descriptor instead.
func (*GetTasksReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{7}
}

func (x *GetTasksReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetTasksReq) GetExecutionId() int32 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *GetTasksReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetTasksReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTasksReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTasksReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetTasksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTasksReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersReq) Reset() {
	*x = GetUsersReq{}
	mi := &file_zentao_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReq) ProtoMessage() {}

func (x *GetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReq.ProtoReflect.Descriptor instead.
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{8}
}

func (x *GetUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUsersAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersAllReq) Reset() {
	*x = GetUsersAllReq{}
	mi := &file_zentao_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersAllReq) ProtoMessage() {}

func (x *GetUsersAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersAllReq.ProtoReflect.Descriptor instead.
func (*GetUsersAllReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{9}
}

type GetCurrentUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserReq) Reset() {
	*x = GetCurrentUserReq{}
	mi := &file_zentao_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserReq) ProtoMessage() {}

func (x *GetCurrentUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserReq.ProtoReflect.Descriptor instead.
func (*GetCurrentUserReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{10}
}

type GetTimelogAnalysisReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	DateFrom      string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelogAnalysisReq) Reset() {
	*x = GetTimelogAnalysisReq{}
	mi := &file_zentao_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelogAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelogAnalysisReq) ProtoMessage() {}

func (x *GetTimelogAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelogAnalysisReq.ProtoReflect.Descriptor instead.
func (*GetTimelogAnalysisReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{11}
}

func (x *GetTimelogAnalysisReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetTimelogAnalysisReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetTimelogAnalysisReq) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetTimelogAnalysisReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetTimelogAnalysisReq) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetTimelogAnalysisReq) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetTimelogDashboardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	DateFrom      string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelogDashboardReq) Reset() {
	*x = GetTimelogDashboardReq{}
	mi := &file_zentao_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelogDashboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelogDashboardReq) ProtoMessage() {}

func (x *GetTimelogDashboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelogDashboardReq.ProtoReflect.Descriptor instead.
func (*GetTimelogDashboardReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{12}
}

func (x *GetTimelogDashboardReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetTimelogDashboardReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetTimelogDashboardReq) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetTimelogDashboardReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetTimelogDashboardReq) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetTimelogDashboardReq) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetTimelogEffortsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	DateFrom      string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimelogEffortsReq) Reset() {
	*x = GetTimelogEffortsReq{}
	mi := &file_zentao_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimelogEffortsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelogEffortsReq) ProtoMessage() {}

func (x *GetTimelogEffortsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelogEffortsReq.ProtoReflect.Descriptor instead.
func (*GetTimelogEffortsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{13}
}

func (x *GetTimelogEffortsReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetTimelogEffortsReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetTimelogEffortsReq) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetTimelogEffortsReq) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *GetTimelogEffortsReq) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetTimelogEffortsReq) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetDashboardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardReq) Reset() {
	*x = GetDashboardReq{}
	mi := &file_zentao_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardReq) ProtoMessage() {}

func (x *GetDashboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardReq.ProtoReflect.Descriptor instead.
func (*GetDashboardReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{14}
}

func (x *GetDashboardReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProjectOverviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int32                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectOverviewReq) Reset() {
	*x = GetProjectOverviewReq{}
	mi := &file_zentao_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectOverviewReq) ProtoMessage() {}

func (x *GetProjectOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectOverviewReq.ProtoReflect.Descriptor instead.
func (*GetProjectOverviewReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{15}
}

func (x *GetProjectOverviewReq) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type GetPersonalTimelogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	GroupBy       string                 `protobuf:"bytes,5,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalTimelogReq) Reset() {
	*x = GetPersonalTimelogReq{}
	mi := &file_zentao_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalTimelogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalTimelogReq) ProtoMessage() {}

func (x *GetPersonalTimelogReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalTimelogReq.ProtoReflect.Descriptor instead.
func (*GetPersonalTimelogReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{16}
}

func (x *GetPersonalTimelogReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetPersonalTimelogReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetPersonalTimelogReq) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetPersonalTimelogReq) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetPersonalTimelogReq) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_zentao_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{17}
}

func (x *SearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SearchReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetInitStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitStatusReq) Reset() {
	*x = GetInitStatusReq{}
	mi := &file_zentao_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitStatusReq) ProtoMessage() {}

func (x *GetInitStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitStatusReq.ProtoReflect.Descriptor instead.
func (*GetInitStatusReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{18}
}

type GetAccountInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountInfoReq) Reset() {
	*x = GetAccountInfoReq{}
	mi := &file_zentao_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoReq) ProtoMessage() {}

func (x *GetAccountInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoReq.ProtoReflect.Descriptor instead.
func (*GetAccountInfoReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{19}
}

type ListSchedulerTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulerTasksReq) Reset() {
	*x = ListSchedulerTasksReq{}
	mi := &file_zentao_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulerTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulerTasksReq) ProtoMessage() {}

func (x *ListSchedulerTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulerTasksReq.ProtoReflect.Descriptor instead.
func (*ListSchedulerTasksReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{20}
}

type CreateSchedulerTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          []byte                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerTaskReq) Reset() {
	*x = CreateSchedulerTaskReq{}
	mi := &file_zentao_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerTaskReq) ProtoMessage() {}

func (x *CreateSchedulerTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerTaskReq.ProtoReflect.Descriptor instead.
func (*CreateSchedulerTaskReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSchedulerTaskReq) GetTask() []byte {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateSchedulerTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task          []byte                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchedulerTaskReq) Reset() {
	*x = UpdateSchedulerTaskReq{}
	mi := &file_zentao_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchedulerTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchedulerTaskReq) ProtoMessage() {}

func (x *UpdateSchedulerTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchedulerTaskReq.ProtoReflect.Descriptor instead.
func (*UpdateSchedulerTaskReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateSchedulerTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSchedulerTaskReq) GetTask() []byte {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteSchedulerTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchedulerTaskReq) Reset() {
	*x = DeleteSchedulerTaskReq{}
	mi := &file_zentao_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchedulerTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchedulerTaskReq) ProtoMessage() {}

func (x *DeleteSchedulerTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchedulerTaskReq.ProtoReflect.Descriptor instead.
func (*DeleteSchedulerTaskReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteSchedulerTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToggleSchedulerTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleSchedulerTaskReq) Reset() {
	*x = ToggleSchedulerTaskReq{}
	mi := &file_zentao_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleSchedulerTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleSchedulerTaskReq) ProtoMessage() {}

func (x *ToggleSchedulerTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleSchedulerTaskReq.ProtoReflect.Descriptor instead.
func (*ToggleSchedulerTaskReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{24}
}

func (x *ToggleSchedulerTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RunSchedulerTaskNowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchedulerTaskNowReq) Reset() {
	*x = RunSchedulerTaskNowReq{}
	mi := &file_zentao_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchedulerTaskNowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchedulerTaskNowReq) ProtoMessage() {}

func (x *RunSchedulerTaskNowReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchedulerTaskNowReq.ProtoReflect.Descriptor instead.
func (*RunSchedulerTaskNowReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{25}
}

func (x *RunSchedulerTaskNowReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSchedulerTaskLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerTaskLogsReq) Reset() {
	*x = GetSchedulerTaskLogsReq{}
	mi := &file_zentao_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerTaskLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerTaskLogsReq) ProtoMessage() {}

func (x *GetSchedulerTaskLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerTaskLogsReq.ProtoReflect.Descriptor instead.
func (*GetSchedulerTaskLogsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{26}
}

func (x *GetSchedulerTaskLogsReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSchedulerAllLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchedulerAllLogsReq) Reset() {
	*x = GetSchedulerAllLogsReq{}
	mi := &file_zentao_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerAllLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerAllLogsReq) ProtoMessage() {}

func (x *GetSchedulerAllLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerAllLogsReq.ProtoReflect.Descriptor instead.
func (*GetSchedulerAllLogsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{27}
}

type TestSchedulerWebhookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSchedulerWebhookReq) Reset() {
	*x = TestSchedulerWebhookReq{}
	mi := &file_zentao_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSchedulerWebhookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSchedulerWebhookReq) ProtoMessage() {}

func (x *TestSchedulerWebhookReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSchedulerWebhookReq.ProtoReflect.Descriptor instead.
func (*TestSchedulerWebhookReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{28}
}

func (x *TestSchedulerWebhookReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PreviewSchedulerReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []byte                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewSchedulerReportReq) Reset() {
	*x = PreviewSchedulerReportReq{}
	mi := &file_zentao_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewSchedulerReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewSchedulerReportReq) ProtoMessage() {}

func (x *PreviewSchedulerReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewSchedulerReportReq.ProtoReflect.Descriptor instead.
func (*PreviewSchedulerReportReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{29}
}

func (x *PreviewSchedulerReportReq) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type MCPHandleActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPHandleActionReq) Reset() {
	*x = MCPHandleActionReq{}
	mi := &file_zentao_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPHandleActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPHandleActionReq) ProtoMessage() {}

func (x *MCPHandleActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPHandleActionReq.ProtoReflect.Descriptor instead.
func (*MCPHandleActionReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{30}
}

func (x *MCPHandleActionReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MCPHandleActionReq) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type MCPHandleActionGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPHandleActionGetReq) Reset() {
	*x = MCPHandleActionGetReq{}
	mi := &file_zentao_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPHandleActionGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPHandleActionGetReq) ProtoMessage() {}

func (x *MCPHandleActionGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPHandleActionGetReq.ProtoReflect.Descriptor instead.
func (*MCPHandleActionGetReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{31}
}

func (x *MCPHandleActionGetReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type MCPHandleListToolsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPHandleListToolsReq) Reset() {
	*x = MCPHandleListToolsReq{}
	mi := &file_zentao_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPHandleListToolsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPHandleListToolsReq) ProtoMessage() {}

func (x *MCPHandleListToolsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPHandleListToolsReq.ProtoReflect.Descriptor instead.
func (*MCPHandleListToolsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{32}
}

type MCPHandleGetToolReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPHandleGetToolReq) Reset() {
	*x = MCPHandleGetToolReq{}
	mi := &file_zentao_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPHandleGetToolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPHandleGetToolReq) ProtoMessage() {}

func (x *MCPHandleGetToolReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPHandleGetToolReq.ProtoReflect.Descriptor instead.
func (*MCPHandleGetToolReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{33}
}

func (x *MCPHandleGetToolReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MCPPingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPPingReq) Reset() {
	*x = MCPPingReq{}
	mi := &file_zentao_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPPingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPPingReq) ProtoMessage() {}

func (x *MCPPingReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPPingReq.ProtoReflect.Descriptor instead.
func (*MCPPingReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{34}
}

type MCPGetProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetProductsReq) Reset() {
	*x = MCPGetProductsReq{}
	mi := &file_zentao_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetProductsReq) ProtoMessage() {}

func (x *MCPGetProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetProductsReq.ProtoReflect.Descriptor instead.
func (*MCPGetProductsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{35}
}

type MCPGetProjectsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetProjectsReq) Reset() {
	*x = MCPGetProjectsReq{}
	mi := &file_zentao_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetProjectsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetProjectsReq) ProtoMessage() {}

func (x *MCPGetProjectsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetProjectsReq.ProtoReflect.Descriptor instead.
func (*MCPGetProjectsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{36}
}

func (x *MCPGetProjectsReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type MCPGetExecutionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetExecutionsReq) Reset() {
	*x = MCPGetExecutionsReq{}
	mi := &file_zentao_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetExecutionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetExecutionsReq) ProtoMessage() {}

func (x *MCPGetExecutionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetExecutionsReq.ProtoReflect.Descriptor instead.
func (*MCPGetExecutionsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{37}
}

func (x *MCPGetExecutionsReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MCPGetExecutionsReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type MCPGetBugsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetBugsReq) Reset() {
	*x = MCPGetBugsReq{}
	mi := &file_zentao_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetBugsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetBugsReq) ProtoMessage() {}

func (x *MCPGetBugsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetBugsReq.ProtoReflect.Descriptor instead.
func (*MCPGetBugsReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{38}
}

func (x *MCPGetBugsReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *MCPGetBugsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MCPGetStoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetStoriesReq) Reset() {
	*x = MCPGetStoriesReq{}
	mi := &file_zentao_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetStoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetStoriesReq) ProtoMessage() {}

func (x *MCPGetStoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetStoriesReq.ProtoReflect.Descriptor instead.
func (*MCPGetStoriesReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{39}
}

func (x *MCPGetStoriesReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type MCPGetTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetTasksReq) Reset() {
	*x = MCPGetTasksReq{}
	mi := &file_zentao_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetTasksReq) ProtoMessage() {}

func (x *MCPGetTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetTasksReq.ProtoReflect.Descriptor instead.
func (*MCPGetTasksReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{40}
}

func (x *MCPGetTasksReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *MCPGetTasksReq) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type MCPGetUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetUsersReq) Reset() {
	*x = MCPGetUsersReq{}
	mi := &file_zentao_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetUsersReq) ProtoMessage() {}

func (x *MCPGetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetUsersReq.ProtoReflect.Descriptor instead.
func (*MCPGetUsersReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{41}
}

type MCPGetTimelogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPGetTimelogReq) Reset() {
	*x = MCPGetTimelogReq{}
	mi := &file_zentao_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPGetTimelogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPGetTimelogReq) ProtoMessage() {}

func (x *MCPGetTimelogReq) ProtoReflect() protoreflect.Message {
	mi := &file_zentao_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPGetTimelogReq.ProtoReflect.Descriptor instead.
func (*MCPGetTimelogReq) Descriptor() ([]byte, []int) {
	return file_zentao_proto_rawDescGZIP(), []int{42}
}

func (x *MCPGetTimelogReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *MCPGetTimelogReq) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *MCPGetTimelogReq) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

var File_zentao_proto protoreflect.FileDescriptor

const file_zentao_proto_rawDesc = "" +
	"\n" +
	"\fzentao.proto\x12\x06zentao\x1a\fcommon.proto\x1a\rapi/api.proto\"\x0f\n" +
	"\rGetVersionReq\"\x10\n" +
	"\x0eHealthCheckReq\"\x10\n" +
	"\x0eGetProductsReq\">\n" +
	"\x0eGetProjectsReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\"n\n" +
	"\x10GetExecutionsReq\x12,\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tprojectIdR\tprojectId\x12,\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\"\x93\x03\n" +
	"\n" +
	"GetBugsReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\x12,\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tprojectIdR\tprojectId\x12\"\n" +
	"\x06status\x18\x03 \x01(\tB\n" +
	"\xb2\xbb\x18\x06statusR\x06status\x12/\n" +
	"\vassigned_to\x18\x04 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12,\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tB\r\xb2\xbb\x18\tstartDateR\tstartDate\x12&\n" +
	"\bend_date\x18\x06 \x01(\tB\v\xb2\xbb\x18\aendDateR\aendDate\x125\n" +
	"\rspecific_date\x18\a \x01(\tB\x10\xb2\xbb\x18\fspecificDateR\fspecificDate\x12\x1c\n" +
	"\x04page\x18\b \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12)\n" +
	"\tpage_size\x18\t \x01(\x05B\f\xb2\xbb\x18\bpageSizeR\bpageSize\"\xa6\x03\n" +
	"\rGetStoriesReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\x12,\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tprojectIdR\tprojectId\x122\n" +
	"\fexecution_id\x18\x03 \x01(\x05B\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\x12/\n" +
	"\vassigned_to\x18\x04 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12,\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tB\r\xb2\xbb\x18\tstartDateR\tstartDate\x12&\n" +
	"\bend_date\x18\x06 \x01(\tB\v\xb2\xbb\x18\aendDateR\aendDate\x125\n" +
	"\rspecific_date\x18\a \x01(\tB\x10\xb2\xbb\x18\fspecificDateR\fspecificDate\x12\x1c\n" +
	"\x04page\x18\b \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12)\n" +
	"\tpage_size\x18\t \x01(\x05B\f\xb2\xbb\x18\bpageSizeR\bpageSize\"\xe3\x02\n" +
	"\vGetTasksReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\x122\n" +
	"\fexecution_id\x18\x02 \x01(\x05B\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\x12/\n" +
	"\vassigned_to\x18\x03 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12\"\n" +
	"\x06status\x18\x04 \x01(\tB\n" +
	"\xb2\xbb\x18\x06statusR\x06status\x12,\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tB\r\xb2\xbb\x18\tstartDateR\tstartDate\x12&\n" +
	"\bend_date\x18\x06 \x01(\tB\v\xb2\xbb\x18\aendDateR\aendDate\x12\x1c\n" +
	"\x04page\x18\a \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12)\n" +
	"\tpage_size\x18\b \x01(\x05B\f\xb2\xbb\x18\bpageSizeR\bpageSize\"V\n" +
	"\vGetUsersReq\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12)\n" +
	"\tpage_size\x18\x02 \x01(\x05B\f\xb2\xbb\x18\bpageSizeR\bpageSize\"\x10\n" +
	"\x0eGetUsersAllReq\"\x13\n" +
	"\x11GetCurrentUserReq\"\xa8\x02\n" +
	"\x15GetTimelogAnalysisReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x12,\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\r\xb2\xbb\x18\tprojectIdR\tprojectId\x122\n" +
	"\fexecution_id\x18\x03 \x01(\tB\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\x12/\n" +
	"\vassigned_to\x18\x04 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12)\n" +
	"\tdate_from\x18\x05 \x01(\tB\f\xb2\xbb\x18\bdateFromR\bdateFrom\x12#\n" +
	"\adate_to\x18\x06 \x01(\tB\n" +
	"\xb2\xbb\x18\x06dateToR\x06dateTo\"\xa9\x02\n" +
	"\x16GetTimelogDashboardReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x12,\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\r\xb2\xbb\x18\tprojectIdR\tprojectId\x122\n" +
	"\fexecution_id\x18\x03 \x01(\tB\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\x12/\n" +
	"\vassigned_to\x18\x04 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12)\n" +
	"\tdate_from\x18\x05 \x01(\tB\f\xb2\xbb\x18\bdateFromR\bdateFrom\x12#\n" +
	"\adate_to\x18\x06 \x01(\tB\n" +
	"\xb2\xbb\x18\x06dateToR\x06dateTo\"\xa7\x02\n" +
	"\x14GetTimelogEffortsReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x12,\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tB\r\xb2\xbb\x18\tprojectIdR\tprojectId\x122\n" +
	"\fexecution_id\x18\x03 \x01(\tB\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\x12/\n" +
	"\vassigned_to\x18\x04 \x01(\tB\x0e\xb2\xbb\x18\n" +
	"assignedToR\n" +
	"assignedTo\x12)\n" +
	"\tdate_from\x18\x05 \x01(\tB\f\xb2\xbb\x18\bdateFromR\bdateFrom\x12#\n" +
	"\adate_to\x18\x06 \x01(\tB\n" +
	"\xb2\xbb\x18\x06dateToR\x06dateTo\"?\n" +
	"\x0fGetDashboardReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\"E\n" +
	"\x15GetProjectOverviewReq\x12,\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05B\r\xb2\xbb\x18\tprojectIdR\tprojectId\"\xe4\x01\n" +
	"\x15GetPersonalTimelogReq\x12%\n" +
	"\aaccount\x18\x01 \x01(\tB\v\xb2\xbb\x18\aaccountR\aaccount\x12,\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\x12)\n" +
	"\tdate_from\x18\x03 \x01(\tB\f\xb2\xbb\x18\bdateFromR\bdateFrom\x12#\n" +
	"\adate_to\x18\x04 \x01(\tB\n" +
	"\xb2\xbb\x18\x06dateToR\x06dateTo\x12&\n" +
	"\bgroup_by\x18\x05 \x01(\tB\v\xb2\xbb\x18\agroupByR\agroupBy\"\xa9\x01\n" +
	"\tSearchReq\x12%\n" +
	"\akeyword\x18\x01 \x01(\tB\v\xb2\xbb\x18\akeywordR\akeyword\x12,\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tproductIdR\tproductId\x12\x1c\n" +
	"\x04page\x18\x03 \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12)\n" +
	"\tpage_size\x18\x04 \x01(\x05B\f\xb2\xbb\x18\bpageSizeR\bpageSize\"\x12\n" +
	"\x10GetInitStatusReq\"\x13\n" +
	"\x11GetAccountInfoReq\"\x17\n" +
	"\x15ListSchedulerTasksReq\"6\n" +
	"\x16CreateSchedulerTaskReq\x12\x1c\n" +
	"\x04task\x18\x01 \x01(\fB\b\xaa\xbb\x18\x04taskR\x04task\"N\n" +
	"\x16UpdateSchedulerTaskReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id\x12\x1c\n" +
	"\x04task\x18\x02 \x01(\fB\b\xaa\xbb\x18\x04taskR\x04task\"0\n" +
	"\x16DeleteSchedulerTaskReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id\"0\n" +
	"\x16ToggleSchedulerTaskReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id\"0\n" +
	"\x16RunSchedulerTaskNowReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id\"1\n" +
	"\x17GetSchedulerTaskLogsReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id\"\x18\n" +
	"\x16GetSchedulerAllLogsReq\"4\n" +
	"\x17TestSchedulerWebhookReq\x12\x19\n" +
	"\x03url\x18\x01 \x01(\tB\a\xb2\xbb\x18\x03urlR\x03url\"?\n" +
	"\x19PreviewSchedulerReportReq\x12\"\n" +
	"\x06params\x18\x01 \x01(\fB\n" +
	"\xaa\xbb\x18\x06paramsR\x06params\"\\\n" +
	"\x12MCPHandleActionReq\x12\"\n" +
	"\x06action\x18\x01 \x01(\tB\n" +
	"\xb2\xbb\x18\x06actionR\x06action\x12\"\n" +
	"\x06params\x18\x02 \x01(\fB\n" +
	"\xaa\xbb\x18\x06paramsR\x06params\";\n" +
	"\x15MCPHandleActionGetReq\x12\"\n" +
	"\x06action\x18\x01 \x01(\tB\n" +
	"\xb2\xbb\x18\x06actionR\x06action\"\x17\n" +
	"\x15MCPHandleListToolsReq\"3\n" +
	"\x13MCPHandleGetToolReq\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\bһ\x18\x04nameR\x04name\"\f\n" +
	"\n" +
	"MCPPingReq\"\x13\n" +
	"\x11MCPGetProductsReq\"A\n" +
	"\x11MCPGetProjectsReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\"q\n" +
	"\x13MCPGetExecutionsReq\x12,\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tprojectIdR\tprojectId\x12,\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\"a\n" +
	"\rMCPGetBugsReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x12\"\n" +
	"\x06status\x18\x02 \x01(\tB\n" +
	"\xb2\xbb\x18\x06statusR\x06status\"@\n" +
	"\x10MCPGetStoriesReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\"r\n" +
	"\x0eMCPGetTasksReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x122\n" +
	"\fexecution_id\x18\x02 \x01(\tB\x0f\xb2\xbb\x18\vexecutionIdR\vexecutionId\"\x10\n" +
	"\x0eMCPGetUsersReq\"\x90\x01\n" +
	"\x10MCPGetTimelogReq\x12,\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\r\xb2\xbb\x18\tproductIdR\tproductId\x12)\n" +
	"\tdate_from\x18\x02 \x01(\tB\f\xb2\xbb\x18\bdateFromR\bdateFrom\x12#\n" +
	"\adate_to\x18\x03 \x01(\tB\n" +
	"\xb2\xbb\x18\x06dateToR\x06dateTo2\xc7\x1e\n" +
	"\rZentaoService\x12J\n" +
	"\n" +
	"GetVersion\x12\x15.zentao.GetVersionReq\x1a\x13.common.ApiResponse\"\x10\xca\xc1\x18\f/api/version\x12L\n" +
	"\vHealthCheck\x12\x16.zentao.HealthCheckReq\x1a\x13.common.ApiResponse\"\x10\xca\xc1\x18\f/api/healthz\x12P\n" +
	"\vGetProducts\x12\x16.zentao.GetProductsReq\x1a\x13.common.ApiResponse\"\x14\xca\xc1\x18\x10/api/v1/products\x12P\n" +
	"\vGetProjects\x12\x16.zentao.GetProjectsReq\x1a\x13.common.ApiResponse\"\x14\xca\xc1\x18\x10/api/v1/projects\x12V\n" +
	"\rGetExecutions\x12\x18.zentao.GetExecutionsReq\x1a\x13.common.ApiResponse\"\x16\xca\xc1\x18\x12/api/v1/executions\x12D\n" +
	"\aGetBugs\x12\x12.zentao.GetBugsReq\x1a\x13.common.ApiResponse\"\x10\xca\xc1\x18\f/api/v1/bugs\x12M\n" +
	"\n" +
	"GetStories\x12\x15.zentao.GetStoriesReq\x1a\x13.common.ApiResponse\"\x13\xca\xc1\x18\x0f/api/v1/stories\x12G\n" +
	"\bGetTasks\x12\x13.zentao.GetTasksReq\x1a\x13.common.ApiResponse\"\x11\xca\xc1\x18\r/api/v1/tasks\x12G\n" +
	"\bGetUsers\x12\x13.zentao.GetUsersReq\x1a\x13.common.ApiResponse\"\x11\xca\xc1\x18\r/api/v1/users\x12Q\n" +
	"\vGetUsersAll\x12\x16.zentao.GetUsersAllReq\x1a\x13.common.ApiResponse\"\x15\xca\xc1\x18\x11/api/v1/users/all\x12[\n" +
	"\x0eGetCurrentUser\x12\x19.zentao.GetCurrentUserReq\x1a\x13.common.ApiResponse\"\x19\xca\xc1\x18\x15/api/v1/users/current\x12f\n" +
	"\x12GetTimelogAnalysis\x12\x1d.zentao.GetTimelogAnalysisReq\x1a\x13.common.ApiResponse\"\x1c\xca\xc1\x18\x18/api/v1/timelog/analysis\x12i\n" +
	"\x13GetTimelogDashboard\x12\x1e.zentao.GetTimelogDashboardReq\x1a\x13.common.ApiResponse\"\x1d\xca\xc1\x18\x19/api/v1/timelog/dashboard\x12c\n" +
	"\x11GetTimelogEfforts\x12\x1c.zentao.GetTimelogEffortsReq\x1a\x13.common.ApiResponse\"\x1b\xca\xc1\x18\x17/api/v1/timelog/efforts\x12S\n" +
	"\fGetDashboard\x12\x17.zentao.GetDashboardReq\x1a\x13.common.ApiResponse\"\x15\xca\xc1\x18\x11/api/v1/dashboard\x12f\n" +
	"\x12GetProjectOverview\x12\x1d.zentao.GetProjectOverviewReq\x1a\x13.common.ApiResponse\"\x1c\xca\xc1\x18\x18/api/v1/project/overview\x12f\n" +
	"\x12GetPersonalTimelog\x12\x1d.zentao.GetPersonalTimelogReq\x1a\x13.common.ApiResponse\"\x1c\xca\xc1\x18\x18/api/v1/personal/timelog\x12D\n" +
	"\x06Search\x12\x11.zentao.SearchReq\x1a\x13.common.ApiResponse\"\x12\xca\xc1\x18\x0e/api/v1/search\x12W\n" +
	"\rGetInitStatus\x12\x18.zentao.GetInitStatusReq\x1a\x13.common.ApiResponse\"\x17\xca\xc1\x18\x13/api/v1/init/status\x12Z\n" +
	"\x0eGetAccountInfo\x12\x19.zentao.GetAccountInfoReq\x1a\x13.common.ApiResponse\"\x18\xca\xc1\x18\x14/api/v1/init/account\x12e\n" +
	"\x12ListSchedulerTasks\x12\x1d.zentao.ListSchedulerTasksReq\x1a\x13.common.ApiResponse\"\x1b\xca\xc1\x18\x17/api/v1/scheduler/tasks\x12g\n" +
	"\x13CreateSchedulerTask\x12\x1e.zentao.CreateSchedulerTaskReq\x1a\x13.common.ApiResponse\"\x1b\xd2\xc1\x18\x17/api/v1/scheduler/tasks\x12k\n" +
	"\x13UpdateSchedulerTask\x12\x1e.zentao.UpdateSchedulerTaskReq\x1a\x13.common.ApiResponse\"\x1f\xda\xc1\x18\x1b/api/v1/scheduler/tasks/:id\x12k\n" +
	"\x13DeleteSchedulerTask\x12\x1e.zentao.DeleteSchedulerTaskReq\x1a\x13.common.ApiResponse\"\x1f\xe2\xc1\x18\x1b/api/v1/scheduler/tasks/:id\x12r\n" +
	"\x13ToggleSchedulerTask\x12\x1e.zentao.ToggleSchedulerTaskReq\x1a\x13.common.ApiResponse\"&\xea\xc1\x18\"/api/v1/scheduler/tasks/:id/toggle\x12o\n" +
	"\x13RunSchedulerTaskNow\x12\x1e.zentao.RunSchedulerTaskNowReq\x1a\x13.common.ApiResponse\"#\xd2\xc1\x18\x1f/api/v1/scheduler/tasks/:id/run\x12r\n" +
	"\x14GetSchedulerTaskLogs\x12\x1f.zentao.GetSchedulerTaskLogsReq\x1a\x13.common.ApiResponse\"$\xca\xc1\x18 /api/v1/scheduler/tasks/:id/logs\x12f\n" +
	"\x13GetSchedulerAllLogs\x12\x1e.zentao.GetSchedulerAllLogsReq\x1a\x13.common.ApiResponse\"\x1a\xca\xc1\x18\x16/api/v1/scheduler/logs\x12p\n" +
	"\x14TestSchedulerWebhook\x12\x1f.zentao.TestSchedulerWebhookReq\x1a\x13.common.ApiResponse\"\"\xd2\xc1\x18\x1e/api/v1/scheduler/test-webhook\x12o\n" +
	"\x16PreviewSchedulerReport\x12!.zentao.PreviewSchedulerReportReq\x1a\x13.common.ApiResponse\"\x1d\xd2\xc1\x18\x19/api/v1/scheduler/preview\x12L\n" +
	"\x0fMCPHandleAction\x12\x1a.zentao.MCPHandleActionReq\x1a\x13.common.ApiResponse\"\b\xd2\xc1\x18\x04/mcp\x12R\n" +
	"\x12MCPHandleActionGet\x12\x1d.zentao.MCPHandleActionGetReq\x1a\x13.common.ApiResponse\"\b\xca\xc1\x18\x04/mcp\x12X\n" +
	"\x12MCPHandleListTools\x12\x1d.zentao.MCPHandleListToolsReq\x1a\x13.common.ApiResponse\"\x0e\xca\xc1\x18\n" +
	"/mcp/tools\x12Z\n" +
	"\x10MCPHandleGetTool\x12\x1b.zentao.MCPHandleGetToolReq\x1a\x13.common.ApiResponse\"\x14\xca\xc1\x18\x10/mcp/tools/:name\x12A\n" +
	"\aMCPPing\x12\x12.zentao.MCPPingReq\x1a\x13.common.ApiResponse\"\r\xca\xc1\x18\t/mcp/ping\x12S\n" +
	"\x0eMCPGetProducts\x12\x19.zentao.MCPGetProductsReq\x1a\x13.common.ApiResponse\"\x11\xca\xc1\x18\r/mcp/products\x12S\n" +
	"\x0eMCPGetProjects\x12\x19.zentao.MCPGetProjectsReq\x1a\x13.common.ApiResponse\"\x11\xca\xc1\x18\r/mcp/projects\x12Y\n" +
	"\x10MCPGetExecutions\x12\x1b.zentao.MCPGetExecutionsReq\x1a\x13.common.ApiResponse\"\x13\xca\xc1\x18\x0f/mcp/executions\x12G\n" +
	"\n" +
	"MCPGetBugs\x12\x15.zentao.MCPGetBugsReq\x1a\x13.common.ApiResponse\"\r\xca\xc1\x18\t/mcp/bugs\x12P\n" +
	"\rMCPGetStories\x12\x18.zentao.MCPGetStoriesReq\x1a\x13.common.ApiResponse\"\x10\xca\xc1\x18\f/mcp/stories\x12J\n" +
	"\vMCPGetTasks\x12\x16.zentao.MCPGetTasksReq\x1a\x13.common.ApiResponse\"\x0e\xca\xc1\x18\n" +
	"/mcp/tasks\x12J\n" +
	"\vMCPGetUsers\x12\x16.zentao.MCPGetUsersReq\x1a\x13.common.ApiResponse\"\x0e\xca\xc1\x18\n" +
	"/mcp/users\x12P\n" +
	"\rMCPGetTimelog\x12\x18.zentao.MCPGetTimelogReq\x1a\x13.common.ApiResponse\"\x10\xca\xc1\x18\f/mcp/timelogB;Z9github.com/yi-nology/zentao-mini/backend/biz/model/zentaob\x06proto3"

var (
	file_zentao_proto_rawDescOnce sync.Once
	file_zentao_proto_rawDescData []byte
)

func file_zentao_proto_rawDescGZIP() []byte {
	file_zentao_proto_rawDescOnce.Do(func() {
		file_zentao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zentao_proto_rawDesc), len(file_zentao_proto_rawDesc)))
	})
	return file_zentao_proto_rawDescData
}

var file_zentao_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_zentao_proto_goTypes = []any{
	(*GetVersionReq)(nil),             // 0: zentao.GetVersionReq
	(*HealthCheckReq)(nil),            // 1: zentao.HealthCheckReq
	(*GetProductsReq)(nil),            // 2: zentao.GetProductsReq
	(*GetProjectsReq)(nil),            // 3: zentao.GetProjectsReq
	(*GetExecutionsReq)(nil),          // 4: zentao.GetExecutionsReq
	(*GetBugsReq)(nil),                // 5: zentao.GetBugsReq
	(*GetStoriesReq)(nil),             // 6: zentao.GetStoriesReq
	(*GetTasksReq)(nil),               // 7: zentao.GetTasksReq
	(*GetUsersReq)(nil),               // 8: zentao.GetUsersReq
	(*GetUsersAllReq)(nil),            // 9: zentao.GetUsersAllReq
	(*GetCurrentUserReq)(nil),         // 10: zentao.GetCurrentUserReq
	(*GetTimelogAnalysisReq)(nil),     // 11: zentao.GetTimelogAnalysisReq
	(*GetTimelogDashboardReq)(nil),    // 12: zentao.GetTimelogDashboardReq
	(*GetTimelogEffortsReq)(nil),      // 13: zentao.GetTimelogEffortsReq
	(*GetDashboardReq)(nil),           // 14: zentao.GetDashboardReq
	(*GetProjectOverviewReq)(nil),     // 15: zentao.GetProjectOverviewReq
	(*GetPersonalTimelogReq)(nil),     // 16: zentao.GetPersonalTimelogReq
	(*SearchReq)(nil),                 // 17: zentao.SearchReq
	(*GetInitStatusReq)(nil),          // 18: zentao.GetInitStatusReq
	(*GetAccountInfoReq)(nil),         // 19: zentao.GetAccountInfoReq
	(*ListSchedulerTasksReq)(nil),     // 20: zentao.ListSchedulerTasksReq
	(*CreateSchedulerTaskReq)(nil),    // 21: zentao.CreateSchedulerTaskReq
	(*UpdateSchedulerTaskReq)(nil),    // 22: zentao.UpdateSchedulerTaskReq
	(*DeleteSchedulerTaskReq)(nil),    // 23: zentao.DeleteSchedulerTaskReq
	(*ToggleSchedulerTaskReq)(nil),    // 24: zentao.ToggleSchedulerTaskReq
	(*RunSchedulerTaskNowReq)(nil),    // 25: zentao.RunSchedulerTaskNowReq
	(*GetSchedulerTaskLogsReq)(nil),   // 26: zentao.GetSchedulerTaskLogsReq
	(*GetSchedulerAllLogsReq)(nil),    // 27: zentao.GetSchedulerAllLogsReq
	(*TestSchedulerWebhookReq)(nil),   // 28: zentao.TestSchedulerWebhookReq
	(*PreviewSchedulerReportReq)(nil), // 29: zentao.PreviewSchedulerReportReq
	(*MCPHandleActionReq)(nil),        // 30: zentao.MCPHandleActionReq
	(*MCPHandleActionGetReq)(nil),     // 31: zentao.MCPHandleActionGetReq
	(*MCPHandleListToolsReq)(nil),     // 32: zentao.MCPHandleListToolsReq
	(*MCPHandleGetToolReq)(nil),       // 33: zentao.MCPHandleGetToolReq
	(*MCPPingReq)(nil),                // 34: zentao.MCPPingReq
	(*MCPGetProductsReq)(nil),         // 35: zentao.MCPGetProductsReq
	(*MCPGetProjectsReq)(nil),         // 36: zentao.MCPGetProjectsReq
	(*MCPGetExecutionsReq)(nil),       // 37: zentao.MCPGetExecutionsReq
	(*MCPGetBugsReq)(nil),             // 38: zentao.MCPGetBugsReq
	(*MCPGetStoriesReq)(nil),          // 39: zentao.MCPGetStoriesReq
	(*MCPGetTasksReq)(nil),            // 40: zentao.MCPGetTasksReq
	(*MCPGetUsersReq)(nil),            // 41: zentao.MCPGetUsersReq
	(*MCPGetTimelogReq)(nil),          // 42: zentao.MCPGetTimelogReq
	(*common.ApiResponse)(nil),        // 43: common.ApiResponse
}
var file_zentao_proto_depIdxs = []int32{
	0,  // 0: zentao.ZentaoService.GetVersion:input_type -> zentao.GetVersionReq
	1,  // 1: zentao.ZentaoService.HealthCheck:input_type -> zentao.HealthCheckReq
	2,  // 2: zentao.ZentaoService.GetProducts:input_type -> zentao.GetProductsReq
	3,  // 3: zentao.ZentaoService.GetProjects:input_type -> zentao.GetProjectsReq
	4,  // 4: zentao.ZentaoService.GetExecutions:input_type -> zentao.GetExecutionsReq
	5,  // 5: zentao.ZentaoService.GetBugs:input_type -> zentao.GetBugsReq
	6,  // 6: zentao.ZentaoService.GetStories:input_type -> zentao.GetStoriesReq
	7,  // 7: zentao.ZentaoService.GetTasks:input_type -> zentao.GetTasksReq
	8,  // 8: zentao.ZentaoService.GetUsers:input_type -> zentao.GetUsersReq
	9,  // 9: zentao.ZentaoService.GetUsersAll:input_type -> zentao.GetUsersAllReq
	10, // 10: zentao.ZentaoService.GetCurrentUser:input_type -> zentao.GetCurrentUserReq
	11, // 11: zentao.ZentaoService.GetTimelogAnalysis:input_type -> zentao.GetTimelogAnalysisReq
	12, // 12: zentao.ZentaoService.GetTimelogDashboard:input_type -> zentao.GetTimelogDashboardReq
	13, // 13: zentao.ZentaoService.GetTimelogEfforts:input_type -> zentao.GetTimelogEffortsReq
	14, // 14: zentao.ZentaoService.GetDashboard:input_type -> zentao.GetDashboardReq
	15, // 15: zentao.ZentaoService.GetProjectOverview:input_type -> zentao.GetProjectOverviewReq
	16, // 16: zentao.ZentaoService.GetPersonalTimelog:input_type -> zentao.GetPersonalTimelogReq
	17, // 17: zentao.ZentaoService.Search:input_type -> zentao.SearchReq
	18, // 18: zentao.ZentaoService.GetInitStatus:input_type -> zentao.GetInitStatusReq
	19, // 19: zentao.ZentaoService.GetAccountInfo:input_type -> zentao.GetAccountInfoReq
	20, // 20: zentao.ZentaoService.ListSchedulerTasks:input_type -> zentao.ListSchedulerTasksReq
	21, // 21: zentao.ZentaoService.CreateSchedulerTask:input_type -> zentao.CreateSchedulerTaskReq
	22, // 22: zentao.ZentaoService.UpdateSchedulerTask:input_type -> zentao.UpdateSchedulerTaskReq
	23, // 23: zentao.ZentaoService.DeleteSchedulerTask:input_type -> zentao.DeleteSchedulerTaskReq
	24, // 24: zentao.ZentaoService.ToggleSchedulerTask:input_type -> zentao.ToggleSchedulerTaskReq
	25, // 25: zentao.ZentaoService.RunSchedulerTaskNow:input_type -> zentao.RunSchedulerTaskNowReq
	26, // 26: zentao.ZentaoService.GetSchedulerTaskLogs:input_type -> zentao.GetSchedulerTaskLogsReq
	27, // 27: zentao.ZentaoService.GetSchedulerAllLogs:input_type -> zentao.GetSchedulerAllLogsReq
	28, // 28: zentao.ZentaoService.TestSchedulerWebhook:input_type -> zentao.TestSchedulerWebhookReq
	29, // 29: zentao.ZentaoService.PreviewSchedulerReport:input_type -> zentao.PreviewSchedulerReportReq
	30, // 30: zentao.ZentaoService.MCPHandleAction:input_type -> zentao.MCPHandleActionReq
	31, // 31: zentao.ZentaoService.MCPHandleActionGet:input_type -> zentao.MCPHandleActionGetReq
	32, // 32: zentao.ZentaoService.MCPHandleListTools:input_type -> zentao.MCPHandleListToolsReq
	33, // 33: zentao.ZentaoService.MCPHandleGetTool:input_type -> zentao.MCPHandleGetToolReq
	34, // 34: zentao.ZentaoService.MCPPing:input_type -> zentao.MCPPingReq
	35, // 35: zentao.ZentaoService.MCPGetProducts:input_type -> zentao.MCPGetProductsReq
	36, // 36: zentao.ZentaoService.MCPGetProjects:input_type -> zentao.MCPGetProjectsReq
	37, // 37: zentao.ZentaoService.MCPGetExecutions:input_type -> zentao.MCPGetExecutionsReq
	38, // 38: zentao.ZentaoService.MCPGetBugs:input_type -> zentao.MCPGetBugsReq
	39, // 39: zentao.ZentaoService.MCPGetStories:input_type -> zentao.MCPGetStoriesReq
	40, // 40: zentao.ZentaoService.MCPGetTasks:input_type -> zentao.MCPGetTasksReq
	41, // 41: zentao.ZentaoService.MCPGetUsers:input_type -> zentao.MCPGetUsersReq
	42, // 42: zentao.ZentaoService.MCPGetTimelog:input_type -> zentao.MCPGetTimelogReq
	43, // 43: zentao.ZentaoService.GetVersion:output_type -> common.ApiResponse
	43, // 44: zentao.ZentaoService.HealthCheck:output_type -> common.ApiResponse
	43, // 45: zentao.ZentaoService.GetProducts:output_type -> common.ApiResponse
	43, // 46: zentao.ZentaoService.GetProjects:output_type -> common.ApiResponse
	43, // 47: zentao.ZentaoService.GetExecutions:output_type -> common.ApiResponse
	43, // 48: zentao.ZentaoService.GetBugs:output_type -> common.ApiResponse
	43, // 49: zentao.ZentaoService.GetStories:output_type -> common.ApiResponse
	43, // 50: zentao.ZentaoService.GetTasks:output_type -> common.ApiResponse
	43, // 51: zentao.ZentaoService.GetUsers:output_type -> common.ApiResponse
	43, // 52: zentao.ZentaoService.GetUsersAll:output_type -> common.ApiResponse
	43, // 53: zentao.ZentaoService.GetCurrentUser:output_type -> common.ApiResponse
	43, // 54: zentao.ZentaoService.GetTimelogAnalysis:output_type -> common.ApiResponse
	43, // 55: zentao.ZentaoService.GetTimelogDashboard:output_type -> common.ApiResponse
	43, // 56: zentao.ZentaoService.GetTimelogEfforts:output_type -> common.ApiResponse
	43, // 57: zentao.ZentaoService.GetDashboard:output_type -> common.ApiResponse
	43, // 58: zentao.ZentaoService.GetProjectOverview:output_type -> common.ApiResponse
	43, // 59: zentao.ZentaoService.GetPersonalTimelog:output_type -> common.ApiResponse
	43, // 60: zentao.ZentaoService.Search:output_type -> common.ApiResponse
	43, // 61: zentao.ZentaoService.GetInitStatus:output_type -> common.ApiResponse
	43, // 62: zentao.ZentaoService.GetAccountInfo:output_type -> common.ApiResponse
	43, // 63: zentao.ZentaoService.ListSchedulerTasks:output_type -> common.ApiResponse
	43, // 64: zentao.ZentaoService.CreateSchedulerTask:output_type -> common.ApiResponse
	43, // 65: zentao.ZentaoService.UpdateSchedulerTask:output_type -> common.ApiResponse
	43, // 66: zentao.ZentaoService.DeleteSchedulerTask:output_type -> common.ApiResponse
	43, // 67: zentao.ZentaoService.ToggleSchedulerTask:output_type -> common.ApiResponse
	43, // 68: zentao.ZentaoService.RunSchedulerTaskNow:output_type -> common.ApiResponse
	43, // 69: zentao.ZentaoService.GetSchedulerTaskLogs:output_type -> common.ApiResponse
	43, // 70: zentao.ZentaoService.GetSchedulerAllLogs:output_type -> common.ApiResponse
	43, // 71: zentao.ZentaoService.TestSchedulerWebhook:output_type -> common.ApiResponse
	43, // 72: zentao.ZentaoService.PreviewSchedulerReport:output_type -> common.ApiResponse
	43, // 73: zentao.ZentaoService.MCPHandleAction:output_type -> common.ApiResponse
	43, // 74: zentao.ZentaoService.MCPHandleActionGet:output_type -> common.ApiResponse
	43, // 75: zentao.ZentaoService.MCPHandleListTools:output_type -> common.ApiResponse
	43, // 76: zentao.ZentaoService.MCPHandleGetTool:output_type -> common.ApiResponse
	43, // 77: zentao.ZentaoService.MCPPing:output_type -> common.ApiResponse
	43, // 78: zentao.ZentaoService.MCPGetProducts:output_type -> common.ApiResponse
	43, // 79: zentao.ZentaoService.MCPGetProjects:output_type -> common.ApiResponse
	43, // 80: zentao.ZentaoService.MCPGetExecutions:output_type -> common.ApiResponse
	43, // 81: zentao.ZentaoService.MCPGetBugs:output_type -> common.ApiResponse
	43, // 82: zentao.ZentaoService.MCPGetStories:output_type -> common.ApiResponse
	43, // 83: zentao.ZentaoService.MCPGetTasks:output_type -> common.ApiResponse
	43, // 84: zentao.ZentaoService.MCPGetUsers:output_type -> common.ApiResponse
	43, // 85: zentao.ZentaoService.MCPGetTimelog:output_type -> common.ApiResponse
	43, // [43:86] is the sub-list for method output_type
	0,  // [0:43] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_zentao_proto_init() }
func file_zentao_proto_init() {
	if File_zentao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zentao_proto_rawDesc), len(file_zentao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zentao_proto_goTypes,
		DependencyIndexes: file_zentao_proto_depIdxs,
		MessageInfos:      file_zentao_proto_msgTypes,
	}.Build()
	File_zentao_proto = out.File
	file_zentao_proto_goTypes = nil
	file_zentao_proto_depIdxs = nil
}
