// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails v3 的 Service（被注册到 application.Options.Services）
 * 同时也是业务层的桥接器：订阅 EventBus，转发到前端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * HideWindow 隐藏主窗口到托盘
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

/**
 * MinimizeToTray 等同于 HideWindow
 */
export function MinimizeToTray(): $CancellablePromise<void> {
    return $Call.ByID(2872916804);
}

/**
 * QuitApp 通过菜单/托盘退出
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3730234565);
}

/**
 * ShowWindow 显示主窗口（前端可调用）
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(31117496);
}
